FROM node:18-slim
WORKDIR /frontend
COPY eindopdrachtCrossplatform ./eindopdrachtCrossplatform
WORKDIR /frontend/eindopdrachtCrossplatform
RUN npm install
EXPOSE 8081
CMD ["npm", "start"]
#docker run -p 8081:8081 frontend