apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sanderroelens/frontend:latest
        ports:
        - containerPort: 8081
        env:
        - name: NODE_ENV
          value: "production"


#minikube start
#kubectl apply -f deployment-frontend.yaml
#minikube service frontend
#http://127.0.0.1:57528/api/swagger-ui/index.html