apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: backend
#kubectl apply -f service-backend.yaml
#http://127.0.0.1:57528/