apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001
  selector:
    app: frontend

#kubectl apply -f service-frontend.yaml
#http://127.0.0.1:57658/
