FROM openjdk:21-jdk-slim
COPY eindopdracht2024-Sander-Roelens/target/JavaBackendOpdracht-0.0.1-SNAPSHOT.jar app1.jar
ENTRYPOINT [ "java", "-jar","app1.jar", "--spring.profiles.active=dev" ]
#docker run -p 8080:8080 backend --spring.profiles.active=dev